### ISSUE TITLE
Improve the UI of user and server info

### ISSUE THREAD

**Issue by Dhruvacube** [The-4th-Hokage/yondaime-hokage#198]
# Simple UI Improvements :)

- **Improve the UI of user and server info.**
The user and server info commands should be improved :) I mean the UI

- **Describe the solution you'd like**
Make the user and server info commands somewhat like these [Dredd](https://dredd-bot.xyz/) and [R.Danny](https://discord.bots.gg/bots/80528701850124288)

- **Describe alternatives you've considered**
Add some relative emojis to the support server. ``Well its done :) from my side``

**Comment by EitoZX** [comment]
I checked `user` & `server` commands. If you don't mind; then can i give a shot to improve it?

**Comment by Dhruvacube** [comment]
fixed
