### ISSUE TITLE
The setup channel disappears before I know what is going on

### ISSUE THREAD

**Issue by mikeysan** [The-4th-Hokage/yondaime-hokage#201]
**Describe the bug**
I couldn't find any information on what the Bot does so I invited it to my server. Once invited I see a message that says to type `)setup` to set up my server. However, while I am still reading to understand the settings available, I get a countdown and then the channel closes.

I have no idea if:
1. Anything was setup Or 
2. What was setup
3. How to make changes to any of the default options that may have been selected.

**To Reproduce**
- Already described above.

**Expected behavior**
A setup channel is created and the user is given as much time as they want to set things up. A reaction to a message at the bottom of the channel could serve as an indication that they are done; then the channel can close.

There should also be a clear message showing how they can make changes to their choices later in the channel that initially showed the setup info.

**Comment by Dhruvacube** [comment]
fixed in v2.0
