### ISSUE TITLE
[ENCHANEMENT] Fix the setup of ")setup" command

### ISSUE THREAD

**Issue by Kira272921** [The-4th-Hokage/yondaime-hokage#236]
**Problem**
The `)setup` command has a timer, which is really annoying as it gets really to setup the bot in a limited time 
Also, the bot just posts the setup messages separately which makes it even harder 
The user can delete the add more setup channels which he/she missed to add due to the countdown thing 

**Describe the solution you'd like**
It would be better if there would be separate command for setting up each setup channel 
Example :- To setup unban log channel, you can make a `)setup unban` similar command which makes it easier for the user to setup the log channels in their server 

**Additional Suggestion**
It would be better if the unban, ban and warns logs would be done a single channel instead, i guess

**Comment by Dhruvacube** [comment]
fixed in v2.0
