### ISSUE TITLE
Fix code scanning alert - Insecure URL

### ISSUE THREAD

**Issue by Dhruvacube** [The-4th-Hokage/yondaime-hokage#327]
Tracking issue for:
- [ ] https://github.com/The-4th-Hokage/yondaime-hokage/security/code-scanning/18

**Comment by EitoZX** [comment]
eh.. that link is **showing up code 404**...
*same with #326 & #325 .*

**Comment by Dhruvacube** [comment]
ohhh its basically that in code somewhere i have put a link with http, it has to be converted to https

**Comment by Dhruvacube** [comment]
and for #326 its basically i have stored a token here https://github.com/The-4th-Hokage/yondaime-hokage/blob/1eda475549f6431387b86c9b22651d2f1683897a/minato_namikaze/bot_files/cogs/weather.py#L122-L122
@EitoZX

**Comment by EitoZX** [comment]
> https://github.com/The-4th-Hokage/yondaime-hokage/blob/1eda475549f6431387b86c9b22651d2f1683897a/minato_namikaze/bot_files/cogs/weather.py#L122-L122

How about storing that token in the `.env` file?

**Comment by Dhruvacube** [comment]
yaaa i know i have goto that, thats why i have left the token like that only

**Comment by Dhruvacube** [comment]
plus that weather code was from redbot cogs code
