### ISSUE TITLE
Command 'aboutanime' raised an exception: ValueError: No such id on MyAnimeList

### ISSUE THREAD

**Issue by Dhruvacube** [The-4th-Hokage/yondaime-hokage#687]
**Describe the bug**
Hybrid command raised an error: Command 'aboutanime' raised an exception: ValueError: No such id on MyAnimeList

**To Reproduce**
1. Type any random mal_id in `aboutanime` comand
2. Wait for some time
3. See error

**Expected behavior**
It should not error and quietly say that dosen't exists in MAL database.

**Additional context**
https://discordapp.com/channels/920190307595874304/920190310942908513/988830767763292172

https://discord.gg/vfXHwS3nmQ

**Comment by eitozx** [comment]
Well, I would like to give a shot. 🚶🏻 Feel free to assign me. 

P.S: I've my exams ongoing rn, so there is possibility of delay

**Comment by Dhruvacube** [comment]
well here i have no concept of assigning an issue, if you have time feel free to make the pr, if you pr is valid then this issue will be automatically assigned to you

**Comment by eitozx** [comment]
💀 lmao

**Comment by Dhruvacube** [comment]
lol

**Comment by Dhruvacube** [comment]
@eitozx even if you make a draft pr with some changes the issue is assigned to you

**Comment by eitozx** [comment]
Hi back again lol. Just tell me where is da cog where you've this command. I find it somewhat difficult to host the bot. So i'll just implement the changes in cog (until u make a guide 💀 )

**Comment by Dhruvacube** [comment]
ahhh wait, here it is https://github.com/The-4th-Hokage/yondaime-hokage/blob/master/minato_namikaze/cogs/anime_and_vocaloids/anime_and_waifu.py
